### ISSUE TITLE
(ab)use Bluesky as an archiver ...

### ISSUE THREAD

**Issue by prjemian** [BCDA-APS/use_bluesky#20]
@tacaswell, @danielballan

I want to (ab)use Bluesky as an archive tool, separate from any other data acquisition at the beam line.  Easy enough to make a list of signals and submit a count() plan to RE() and monitor them at regular intervals.  All this goes into a python script that is run in the background.

It's a bit more tricky to close the archiving stream with a stop document if num=None and the "archiver" (Bluesky script) is run as a background process.  How can I queue up a RE.stop() command in response to the "python is quitting" process?

Even trickier is how to make the plan emit event documents at the natural update rate of each signal.  Easiest example I can conjure is a motor which has a setpoint and a readback.  Many readback events are generated for a single setpoint event.  Can I (how can I) write a plan that will monitor several signals, each with its own update schedule which might be irregular, and emit event documents when any signal updates?  Configurable parts are minimum interval to group updates together and maximum interval to report any value even if not updated.

Is it even allowed to emit an event document with value(s) for only one or a subset of the signals in the event descriptor document?  Each event would be an update just for that signal (or cluster of signal updates).

Can you identify plans (example or actual) that use monitor() and unmonitor()?  My search of bluesky/plans.py turned up empty.

Thanks,
   Pete

**Comment by tacaswell** [comment]
see https://nsls-ii.github.io/bluesky/async.html#monitoring for how to monitor will monitor each signal at their natural rate, but will not do any grouping or set a maximum period (as it is just listening to camonitor, but that can be configured in your IOC).  Because this is tied to camonitor it is tied to a single PV -> one signal per event.

https://github.com/NSLS-II/bluesky/blob/master/bluesky/tests/test_new_examples.py <- some tests
https://github.com/NSLS-II/bluesky/blob/master/bluesky/plans.py#L2903 <- ramp_plan uses monitor internally.
https://github.com/NSLS-II/bluesky/blob/master/bluesky/spec_api.py#L295 <- 'SPEC' plans currently use them, will be moved to diagnostic pre-processor

To read a bunch of things when any of them change, something along the lines of (the untested!) code may work

```python
@run_decorator
def bunch_monitor(sigs, max_time):
     last_cb = None
     while True:
         # make a status sub-class that when it times out reports success
         st = StatusThatTimesoutSuccess(max_time)
         # subscribe it to all of the signals so if any updates, read them all
         def _st_cb(*args, **kwargs):
             st._finished()

         for s in sig:
             # remove the old callbacks
             if last_cb is not None:
                 sig.reset_sub(last_cb)
             # subscribe to flip the status object on any update to value, this will set up
             # monitoring under the hood automatically
             sig.subscribe(_st_cb, run=False)
         last_cb = _st_cb
         # wait for the status (this might need a bit of munging to play nice with RE)
         yield from bp.wait_for(st)
         # if it times out or anything updates read everything
         yield from trigger_and_read(sigs)
         yield from bp.checkpoint()  # do not rewind if paused / interrupted.
```

See https://docs.python.org/3/library/atexit.html for a way to stop on exit, I think registering `RE.stop` will do the trick, but given that when the RE is running the main thread is owned by the event loop it is not clear that there is a graceful way to get that to run.

```python
RE(forever_plan())
RE.stop()
```

might also 'just work' because we pause on `Ctl-c` by capturing signals.  Python will then happily continue to `RE.stop()`, emit your stop document and then exit.

**Comment by prjemian** [comment]
Kicking this down the road.  Not enough interest to solve this now.
